name: deploy json data
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout covid19
        uses: actions/checkout@v2
        with:
          ref: 'development'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tool/requirements.txt
      - name: Run script
        run: |
          python tool/main.py
      - name: move xlsx files
        run: |
          mv data/*.xlsx dist/data
      - run: git diff

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data dist
          git commit -m "update json data `date '+%Y-%m-%dT%H:%M:%SZ'`"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
          labels: auto_merge
          branch-suffix: 'short-commit-hash'
